### ISSUE TITLE
A Necessary Function is Missing

### ISSUE THREAD

**Issue by DeepSkyColors** [farhi/matlab-astrometry#1]
'Astrometry.m' and Several Functions in 'Private Folder' need 'fits_get_wcs' Function to run, But I'm not able to find 'fits_get_wcs.m' in download list.  Any Solution?

**Comment by farhi** [comment]
I just push the missing function with commit https://github.com/farhi/matlab-astrometry/commit/dba0727143ed90fe565745a2511de14f52955fc6

In principle, this function is never called, as the WCS data is stored in the astrometry result, and it is not needed to read it from the file. It may still be needed to e.g. build a stand-alone/runtime/compiled version.

Thanks for reporting. Closing issue.
